[technote]
id = "SITCOMTN-157"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-157.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-157"
github_default_branch = "main"
date_created = 2025-03-07T17:50:24Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Keith"
name.family = "Bechtol"
internal_id = "bechtolk"

[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
